energy:
  image: meteorhacks/meteord:devbuild
  ports:
   - "8080:80"
  links:
   - mongo
  environment:
   - REPO=https://github.com/evanberger/for_arthur
   - ROOT_URL=http://energy.local

mongo:
  image: mongo:latest
